import { useI18n } from "@/lib/i18n";

/**
 * Copy for the mobile-app shell (5 tabs). Kept separate from the legacy
 * site dictionary so the app screens stay self-contained.
 */
export const appCopy = {
  pt: {
    "brand.name": "Joana & Diogo",
    "brand.date": "19 Setembro 2026",

    "tab.home": "Início",
    "tab.place": "Local",
    "tab.photos": "Fotos",
    "tab.rsvp": "RSVP",
    "tab.more": "Mais",

    "home.hero1": "A nossa maior viagem",
    "home.hero2": "começa agora",
    "home.countdown": "A contagem começou",
    "home.countdownSub": "para o nosso grande dia",
    "home.days": "Dias",
    "home.hours": "Horas",
    "home.mins": "Min",
    "home.secs": "Seg",
    "home.cta": "Confirmar presença",
    "home.q1": "Como chegar",
    "home.q2": "Fotografias",
    "home.q3": "Mensagem",
    "home.q4": "Presentes",
    "home.ceremony": "A cerimónia",
    "home.ceremonyDesc": "Freamunde, Portugal · Cerimónia às 14h00",
    "home.arrived": "O grande dia chegou",

    "place.kicker": "O local",
    "place.address": "Rua da Glicínia, Freamunde",
    "place.time": "Cerimónia e receção às 14h00",
    "place.maps": "Abrir no Google Maps",
    "place.how": "Como chegar",
    "place.porto": "Porto",
    "place.portoV": "30 min de carro",
    "place.aveiro": "Aveiro",
    "place.aveiroV": "1h00 de carro",
    "place.airport": "Aeroporto",
    "place.airportV": "35 min de carro",
    "place.parking": "Estacionamento",
    "place.parkingV": "Gratuito no local",
    "place.stay": "Alojamento",
    "place.stayDesc":
      "A quinta dispõe de alojamento no local. Check-in a partir das 15h00. Para reservas, contactem-nos diretamente.",
    "place.stayCta": "Pedir quarto",
    "place.dress": "Dress code",
    "place.dressDesc":
      "Sintam-se confortáveis e incríveis. Guardem o branco apenas para a noiva — cores alegres são bem-vindas.",

    "photos.kicker": "Fotografias",
    "photos.sub": "o nosso álbum oficial",
    "photos.add": "Adicionar as tuas fotos",
    "photos.note": "Todas as fotografias são guardadas no álbum oficial do casamento.",
    "photos.sheetTitle": "Adicionar fotografias",
    "photos.sheetSub": "escolhe os momentos que queres partilhar",
    "photos.pick": "Escolher fotos",
    "photos.sending": "A enviar as tuas fotos…",
    "photos.doneTitle": "Fotos adicionadas!",
    "photos.doneDesc": "Já estão no álbum oficial dos noivos.",
    "photos.finish": "Concluir",
    "photos.empty": "Ainda não há fotografias publicadas.",
    "photos.close": "Fechar",

    "rsvp.title": "Confirmar presença",
    "rsvp.sub": "Por favor responde até 1 de Agosto de 2026",
    "rsvp.s1": "Quem vem?",
    "rsvp.s2": "Vais estar presente?",
    "rsvp.s3": "Alguns detalhes",
    "rsvp.s4": "Está tudo certo?",
    "rsvp.name": "Nome completo",
    "rsvp.email": "Email",
    "rsvp.phone": "Contacto telefónico",
    "rsvp.yes": "Sim, com alegria",
    "rsvp.no": "Infelizmente não",
    "rsvp.people": "Número de pessoas",
    "rsvp.diet": "Restrições alimentares",
    "rsvp.song": "Música favorita",
    "rsvp.note": "Mensagem para os noivos",
    "rsvp.back": "Voltar",
    "rsvp.next": "Continuar",
    "rsvp.send": "Enviar resposta",
    "rsvp.sending": "A enviar…",
    "rsvp.presence": "Presença",
    "rsvp.none": "—",
    "rsvp.thanks": "Obrigado!",
    "rsvp.thanksDesc":
      "A tua resposta foi recebida com amor. Mal podemos esperar por ti no dia 19 de Setembro!",
    "rsvp.again": "Editar a minha resposta",
    "rsvp.errName": "Indica o teu nome completo (mín. 3 letras).",
    "rsvp.errEmail": "Email inválido.",
    "rsvp.errPhone": "Indica 9 dígitos (ex: 912345678).",
    "rsvp.errAttend": "Indica se vais estar presente.",
    "rsvp.errSubmit": "Algo correu mal. Tenta novamente.",

    "more.title": "Mais",
    "more.messages": "Livro de mensagens",
    "more.gifts": "Lista de presentes",
    "more.faq": "Perguntas frequentes",
    "more.whatsapp": "Falar connosco",
    "more.private": "Área privada",
    "more.privateSub": "Os noivos",
    "more.footer": "Feito com ♡ para a nossa maior viagem",
    "gifts.kicker": "Com gratidão",
    "gifts.title": "Presentes",
    "gifts.desc":
      "A vossa presença é o nosso maior presente. Caso queiram contribuir, deixamos os nossos dados.",
    "gifts.iban": "Conta nacional (Portugal)",
    "gifts.rev": "Revolut (conta conjunta)",
    "gifts.mbway": "MB WAY",
    "gifts.copy": "Copiar",
    "gifts.copied": "Copiado!",
    "faq.title": "Perguntas frequentes",
    "faq.sub": "tudo o que precisas de saber",
    "msg.title": "Deixa-nos uma mensagem",
    "msg.sub": "as tuas palavras guardam-se para sempre",
  },
  en: {
    "brand.name": "Joana & Diogo",
    "brand.date": "19 September 2026",

    "tab.home": "Home",
    "tab.place": "Venue",
    "tab.photos": "Photos",
    "tab.rsvp": "RSVP",
    "tab.more": "More",

    "home.hero1": "Our greatest journey",
    "home.hero2": "begins now",
    "home.countdown": "The countdown has begun",
    "home.countdownSub": "to our big day",
    "home.days": "Days",
    "home.hours": "Hours",
    "home.mins": "Min",
    "home.secs": "Sec",
    "home.cta": "RSVP now",
    "home.q1": "Getting there",
    "home.q2": "Photos",
    "home.q3": "Message",
    "home.q4": "Gifts",
    "home.ceremony": "The ceremony",
    "home.ceremonyDesc": "Freamunde, Portugal · Ceremony at 2:00 pm",
    "home.arrived": "The big day is here",

    "place.kicker": "The venue",
    "place.address": "Rua da Glicínia, Freamunde",
    "place.time": "Ceremony and reception at 2:00 pm",
    "place.maps": "Open in Google Maps",
    "place.how": "Getting there",
    "place.porto": "Porto",
    "place.portoV": "30 min by car",
    "place.aveiro": "Aveiro",
    "place.aveiroV": "1h00 by car",
    "place.airport": "Airport",
    "place.airportV": "35 min by car",
    "place.parking": "Parking",
    "place.parkingV": "Free on site",
    "place.stay": "Accommodation",
    "place.stayDesc":
      "The estate has rooms on site. Check-in from 3:00 pm. For bookings, please contact us directly.",
    "place.stayCta": "Request a room",
    "place.dress": "Dress code",
    "place.dressDesc":
      "Be comfortable and stunning. Please leave white for the bride — joyful colours are welcome.",

    "photos.kicker": "Photos",
    "photos.sub": "our official album",
    "photos.add": "Add your photos",
    "photos.note": "All photos are kept in the official wedding album.",
    "photos.sheetTitle": "Add photos",
    "photos.sheetSub": "choose the moments you want to share",
    "photos.pick": "Choose photos",
    "photos.sending": "Sending your photos…",
    "photos.doneTitle": "Photos added!",
    "photos.doneDesc": "They are now in the couple's official album.",
    "photos.finish": "Done",
    "photos.empty": "No photos published yet.",
    "photos.close": "Close",

    "rsvp.title": "RSVP",
    "rsvp.sub": "Please reply by 1 August 2026",
    "rsvp.s1": "Who's coming?",
    "rsvp.s2": "Will you be there?",
    "rsvp.s3": "A few details",
    "rsvp.s4": "All correct?",
    "rsvp.name": "Full name",
    "rsvp.email": "Email",
    "rsvp.phone": "Phone number",
    "rsvp.yes": "Yes, with joy",
    "rsvp.no": "Sadly, no",
    "rsvp.people": "Number of guests",
    "rsvp.diet": "Dietary restrictions",
    "rsvp.song": "Favourite song",
    "rsvp.note": "Message for the couple",
    "rsvp.back": "Back",
    "rsvp.next": "Continue",
    "rsvp.send": "Send reply",
    "rsvp.sending": "Sending…",
    "rsvp.presence": "Attending",
    "rsvp.none": "—",
    "rsvp.thanks": "Thank you!",
    "rsvp.thanksDesc":
      "Your reply has been received with love. We can't wait to see you on 19 September!",
    "rsvp.again": "Edit my reply",
    "rsvp.errName": "Please enter your full name (min. 3 letters).",
    "rsvp.errEmail": "Invalid email.",
    "rsvp.errPhone": "Enter 9 digits (e.g. 912345678).",
    "rsvp.errAttend": "Please tell us if you'll attend.",
    "rsvp.errSubmit": "Something went wrong. Please try again.",

    "more.title": "More",
    "more.messages": "Guest book",
    "more.gifts": "Gift list",
    "more.faq": "Frequently asked questions",
    "more.whatsapp": "Talk to us",
    "more.private": "Private area",
    "more.privateSub": "The couple",
    "more.footer": "Made with ♡ for our greatest journey",
    "gifts.kicker": "With gratitude",
    "gifts.title": "Gifts",
    "gifts.desc":
      "Your presence is our greatest gift. If you'd like to contribute, here are our details.",
    "gifts.iban": "National account (Portugal)",
    "gifts.rev": "Revolut (joint account)",
    "gifts.mbway": "MB WAY",
    "gifts.copy": "Copy",
    "gifts.copied": "Copied!",
    "faq.title": "Frequently asked questions",
    "faq.sub": "everything you need to know",
    "msg.title": "Leave us a message",
    "msg.sub": "your words are kept forever",
  },
} as const;

export type AppCopyKey = keyof (typeof appCopy)["pt"];

export function useApp() {
  const { lang, setLang } = useI18n();
  const a = (k: AppCopyKey) => appCopy[lang][k] ?? k;
  return { lang, setLang, a };
}
